

const tableColaboradores = [
    {
        id: 1,
        nome: "Jadson Santos",
        setorId: "Direcao",
        departamentoId: "RH",
        cargoId: "Diretor",
        imagem: "",
        cpf: "954.885.975-00",
        email: "email@email.com",
        cidade: "cidade",
        bairro: "bairro",
        rua: "rua",
        numero: 999,
        salario: "R$4.500,00",
        cargaHoraria: "54h/semana",
        homeOfice: "Sim",
        bem: "00025",
        observacao: ""
    },
    {
        id: 2,
        nome: "Jadson Santos",
        setorId: "direcaoRH",
        departamentoId: "Contabil",
        cargoId: "Diretor",
        imagem: "",
        cpf: "954.885.975-00",
        email: "email@email.com",
        cidade: "cidade",
        bairro: "bairro",
        rua: "rua",
        numero: 999,
        salario: "R$4.500,00",
        cargaHoraria: "54h/semana",
        homeOfice: "Sim",
        bem: "00025",
        observacao: ""
    },
    {
        id: 3,
        nome: "Jadson Santos",
        setorId: "direcaoRH",
        departamentoId: "Gerencia",
        cargoId: "Diretor",
        imagem: "",
        cpf: "954.885.975-00",
        email: "email@email.com",
        cidade: "cidade",
        bairro: "bairro",
        rua: "rua",
        numero: 999,
        salario: "R$4.500,00",
        cargaHoraria: "54h/semana",
        homeOfice: "Sim",
        bem: "00025",
        observacao: ""
    },
    {
        id: 4,
        nome: "Jadson Santos",
        setorId: "direcaoRH",
        departamentoId: "Diretoria",
        cargoId: "Diretor",
        imagem: "",
        cpf: "954.885.975-00",
        email: "email@email.com",
        cidade: "cidade",
        bairro: "bairro",
        rua: "rua",
        numero: 999,
        salario: "R$4.500,00",
        cargaHoraria: "54h/semana",
        homeOfice: "Sim",
        bem: "00025",
        observacao: ""
    },
    {
        id: 5,
        nome: "Jadson Santos",
        setorId: "direcaoRH",
        departamentoId: "RH",
        cargoId: "Diretor",
        imagem: "",
        cpf: "954.885.975-00",
        email: "email@email.com",
        cidade: "cidade",
        bairro: "bairro",
        rua: "rua",
        numero: 999,
        salario: "R$4.500,00",
        cargaHoraria: "54h/semana",
        homeOfice: "Sim",
        bem: "00025",
        observacao: ""
    },
    {
        id: 6,
        nome: "Jadson Santos",
        setorId: "direcaoRH",
        departamentoId: "Gerencia",
        cargoId: "Auxiliar",
        imagem: "",
        cpf: "954.885.975-00",
        email: "email@email.com",
        cidade: "cidade",
        bairro: "bairro",
        rua: "rua",
        numero: 999,
        salario: "R$4.500,00",
        cargaHoraria: "54h/semana",
        homeOfice: "Sim",
        bem: "00025",
        observacao: ""
    },
    {
        id: 7,
        nome: "Jadson Santos",
        setorId: "direcaoRH",
        departamentoId: "Producao",
        cargoId: "Diretor",
        imagem: "",
        cpf: "954.885.975-00",
        email: "email@email.com",
        cidade: "cidade",
        bairro: "bairro",
        rua: "rua",
        numero: 999,
        salario: "R$4.500,00",
        cargaHoraria: "54h/semana",
        homeOfice: "Sim",
        bem: "00025",
        observacao: ""
    },
    {
        id: 8,
        nome: "Jobson Barreto",
        setorId: "Vendas",
        departamentoId: "Producao",
        cargoId: "Vendedor",
        imagem: "",
        cpf: "954.885.975-00",
        email: "email@email.com",
        cidade: "cidade",
        bairro: "bairro",
        rua: "rua",
        numero: 999,
        salario: "R$4.500,00",
        cargaHoraria: "54h/semana",
        homeOfice: "Sim",
        bem: "00025",
        observacao: ""
    },
    {
        id: 9,
        nome: "Werik Jahel",
        setorId: "Vendas",
        departamentoId: "Producao",
        cargoId: "Vendedor",
        imagem: "",
        cpf: "954.885.975-00",
        email: "email@email.com",
        cidade: "cidade",
        bairro: "bairro",
        rua: "rua",
        numero: 999,
        salario: "R$4.500,00",
        cargaHoraria: "54h/semana",
        homeOfice: "Sim",
        bem: "00025",
        observacao: ""
    },
    {
        id: 10,
        nome: "Fabricio Santos",
        setorId: "Vendas",
        departamentoId: "Producao",
        cargoId: "Vendedor",
        imagem: "",
        cpf: "954.885.975-00",
        email: "email@email.com",
        cidade: "cidade",
        bairro: "bairro",
        rua: "rua",
        numero: 999,
        salario: "R$4.500,00",
        cargaHoraria: "54h/semana",
        homeOfice: "Sim",
        bem: "00025",
        observacao: ""
    }

]; 

export default tableColaboradores;